
name: Run COBOL Program

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GnuCOBOL
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: List files
        run: ls -R

      - name: Compile COBOL program
        run: cobc -x "projeto1-hello-world-cobol/02_Add.cob" -o "02_Add"

      - name: Execute COBOL program
        run: ./02_Add
